package rime

import (
	"bufio"
	"errors"
	"fmt"
	"os"
	"os/exec"
	"path/filepath"
	"sort"
	"strconv"
	"strings"
	"time"

	"github.com/frankichen/fydeRhythm/ubuntu-client/internal/config"
	"github.com/frankichen/fydeRhythm/ubuntu-client/internal/model"
)

const (
	dictName    = "fyderhythm_personal"
	markerBegin = "# BEGIN FYDERHYTHM PERSONAL SYNC"
	markerEnd   = "# END FYDERHYTHM PERSONAL SYNC"
)

func Render(cfg config.Config, entries map[string]model.LexiconEntry) (int, error) {
	if err := os.MkdirAll(cfg.RimeUserDir, 0o700); err != nil {
		return 0, err
	}
	count, err := writeDictionary(cfg, entries)
	if err != nil {
		return 0, err
	}
	if err := ensureSchemaPatch(cfg); err != nil {
		return 0, err
	}
	return count, nil
}

func writeDictionary(cfg config.Config, entries map[string]model.LexiconEntry) (int, error) {
	path := filepath.Join(cfg.RimeUserDir, dictName+".dict.yaml")
	tmp := path + ".tmp"
	f, err := os.OpenFile(tmp, os.O_CREATE|os.O_TRUNC|os.O_WRONLY, 0o600)
	if err != nil {
		return 0, err
	}
	w := bufio.NewWriter(f)
	_, _ = fmt.Fprintf(w, "# Generated by fyderhythm-sync. Do not edit while sync is enabled.\n")
	_, _ = fmt.Fprintf(w, "# encoding: utf-8\n---\nname: %s\nversion: %q\nsort: by_weight\nuse_preset_vocabulary: false\ncolumns:\n  - text\n  - code\n  - weight\n...\n", dictName, time.Now().Format("2006.01.02.150405"))

	ids := make([]string, 0, len(entries))
	for id := range entries {
		ids = append(ids, id)
	}
	sort.Strings(ids)
	seen := make(map[string]struct{})
	count := 0
	for _, id := range ids {
		entry := entries[id]
		if entry.Deleted {
			continue
		}
		phrase := cleanField(entry.Phrase)
		if phrase == "" {
			continue
		}
		codes := uniqueCodes(entry.Shortcut, entry.Code)
		weight := entry.Weight
		if weight <= 0 {
			weight = 100
		}
		if weight > 100000 {
			weight = 100000
		}
		for _, code := range codes {
			key := phrase + "\x00" + code
			if _, ok := seen[key]; ok {
				continue
			}
			seen[key] = struct{}{}
			_, _ = fmt.Fprintf(w, "%s\t%s\t%d\n", phrase, code, weight)
			count++
		}
	}
	if err := w.Flush(); err != nil {
		f.Close()
		return 0, err
	}
	if err := f.Close(); err != nil {
		return 0, err
	}
	if err := os.Rename(tmp, path); err != nil {
		return 0, err
	}
	return count, nil
}

func uniqueCodes(values ...string) []string {
	seen := make(map[string]struct{})
	var out []string
	for _, value := range values {
		value = strings.ToLower(strings.TrimSpace(value))
		if value == "" || strings.ContainsAny(value, "\t\r\n ") {
			continue
		}
		if _, ok := seen[value]; ok {
			continue
		}
		seen[value] = struct{}{}
		out = append(out, value)
	}
	return out
}

func cleanField(value string) string {
	value = strings.TrimSpace(value)
	value = strings.ReplaceAll(value, "\t", " ")
	value = strings.ReplaceAll(value, "\r", " ")
	value = strings.ReplaceAll(value, "\n", " ")
	return strings.TrimSpace(value)
}

func ensureSchemaPatch(cfg config.Config) error {
	path := filepath.Join(cfg.RimeUserDir, cfg.SchemaID+".custom.yaml")
	managedBody := strings.Join([]string{
		markerBegin,
		"  \"engine/translators/+\":",
		"    - table_translator@fyderhythm_personal",
		"  fyderhythm_personal:",
		"    dictionary: fyderhythm_personal",
		"    enable_user_dict: false",
		"    enable_sentence: false",
		"    enable_completion: false",
		"    initial_quality: 0.2",
		markerEnd,
	}, "\n")

	data, err := os.ReadFile(path)
	if errors.Is(err, os.ErrNotExist) {
		content := "# Generated by fyderhythm-sync\npatch:\n" + managedBody + "\n"
		return writeBackupSafe(path, []byte(content))
	}
	if err != nil {
		return err
	}
	text := string(data)
	if begin := strings.Index(text, markerBegin); begin >= 0 {
		endRelative := strings.Index(text[begin:], markerEnd)
		if endRelative < 0 {
			return fmt.Errorf("%s 中的 fydeRhythm 标记不完整", path)
		}
		end := begin + endRelative + len(markerEnd)
		updated := text[:begin] + managedBody + text[end:]
		return writeBackupSafe(path, []byte(updated))
	}
	if !hasRootPatch(text) {
		return fmt.Errorf("%s 已存在但没有顶层 patch:，为避免破坏配置未自动修改", path)
	}
	if !strings.HasSuffix(text, "\n") {
		text += "\n"
	}
	text += managedBody + "\n"
	return writeBackupSafe(path, []byte(text))
}

func hasRootPatch(text string) bool {
	scanner := bufio.NewScanner(strings.NewReader(text))
	for scanner.Scan() {
		line := strings.TrimSpace(scanner.Text())
		if strings.HasPrefix(scanner.Text(), "patch:") && line == "patch:" {
			return true
		}
	}
	return false
}

func writeBackupSafe(path string, data []byte) error {
	if current, err := os.ReadFile(path); err == nil {
		if string(current) == string(data) {
			return nil
		}
		backup := path + ".backup." + strconv.FormatInt(time.Now().Unix(), 10)
		if err := os.WriteFile(backup, current, 0o600); err != nil {
			return fmt.Errorf("备份现有配置: %w", err)
		}
	}
	tmp := path + ".tmp"
	if err := os.WriteFile(tmp, data, 0o600); err != nil {
		return err
	}
	return os.Rename(tmp, path)
}

func Deploy(cfg config.Config) error {
	deployer, err := exec.LookPath("rime_deployer")
	if err != nil {
		return errors.New("未找到 rime_deployer；词典已写入，但需要在 Fcitx5 中手动重新部署 Rime")
	}
	shared := findSharedDataDir()
	buildDir := filepath.Join(cfg.RimeUserDir, "build")
	if err := os.MkdirAll(buildDir, 0o700); err != nil {
		return err
	}
	args := []string{"--build", cfg.RimeUserDir}
	if shared != "" {
		args = append(args, shared, buildDir)
	}
	cmd := exec.Command(deployer, args...)
	output, err := cmd.CombinedOutput()
	if err != nil {
		return fmt.Errorf("Rime 重新部署失败: %w: %s", err, strings.TrimSpace(string(output)))
	}
	if remote, err := exec.LookPath("fcitx5-remote"); err == nil {
		_ = exec.Command(remote, "-r").Run()
	}
	return nil
}

func findSharedDataDir() string {
	for _, path := range []string{"/usr/share/rime-data", "/usr/local/share/rime-data", "/usr/share/fcitx5/rime"} {
		if stat, err := os.Stat(path); err == nil && stat.IsDir() {
			return path
		}
	}
	return ""
}
